name: hci4ai
channels:
  - defaults
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - icu=73.1
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libkrb5=1.21.3
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=3.0.17
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pywin32=311
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - flatbuffers==25.2.10
      - gast==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.8.0
      - idna==3.10
      - joblib==1.5.1
      - keras==2.13.1
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - numba==0.61.2
      - oauthlib==3.3.1
      - opencv-python-headless==4.8.1.78
      - opt-einsum==3.4.0
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - shap==0.48.0
      - slicer==0.0.8
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.5.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
